name: PowerShell Module CI

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Cache PowerShell modules
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: ~/.local/share/powershell/Modules
          key: ${{ runner.os }}-pwshmodules-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pwshmodules-

      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force -Scope CurrentUser

      - name: Run Tests
        shell: pwsh
        run: |
          if (Test-Path ./Tests/PesterConfiguration.psd1) {
            Invoke-Pester -Configuration (Import-PowerShellDataFile ./Tests/PesterConfiguration.psd1)
          } else {
            Write-Error "PesterConfiguration.psd1 not found!"
            exit 1
          }

      - name: Check if coverage.xml exists
        id: check_coverage
        shell: pwsh
        run: |
          if (Test-Path './coverage.xml') {
            echo "coverage_exists=true" >> $env:GITHUB_OUTPUT
          } else {
            echo "coverage_exists=false" >> $env:GITHUB_OUTPUT
          }

      - name: Upload coverage reports to Codecov
        if: success() && steps.check_coverage.outputs.coverage_exists == 'true'
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml